### ISSUE TITLE
get errors

### ISSUE THREAD

**Issue by 33site** [yasuoyuhao/BitcoinBlockChainMinimalist#1]
Could not determine generated file paths for Core Data code generation: Error Domain=com.apple.dt.ModelingTools Code=1 "Error, failed to read Core Data data model from /Users/emeRson/Desktop/bitcoin/BitcoinBlockChainMinimalist/BitcoinBlockChainMinimalist.xcdatamodeld/BitcoinBlockChainMinimalist.xcdatamodel: unknown model format" UserInfo={NSFilePath=/Users/emeRson/Desktop/bitcoin/BitcoinBlockChainMinimalist/BitcoinBlockChainMinimalist.xcdatamodeld/BitcoinBlockChainMinimalist.xcdatamodel, NSLocalizedDescription=Error, failed to read Core Data data model from /Users/emeRson/Desktop/bitcoin/BitcoinBlockChainMinimalist/BitcoinBlockChainMinimalist.xcdatamodeld/BitcoinBlockChainMinimalist.xcdatamodel: unknown model format}

**Comment by yuhao-git-star** [comment]
Solve the problem, please try again Thank you.

**Comment by 33site** [comment]
謝謝。。詳細看了，原來你是台灣人，我是香港人^^
我另外有一個APP 有些問題，可以幫我看看嗎？謝謝

2017-11-03 14:47 GMT+08:00 yuhaoyasuo <notifications@github.com>:
